### ISSUE TITLE
Invalid django project directory

### ISSUE THREAD

**Issue by khaleeboss** [cstrap/python-vuejs#23]
* Python and Vue.js integration version:
* Python version:
* Operating System:

### Description

when running "pyvue djstartvueapp frontend" i get an error that says Invalid django project directory

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by cstrap** [comment]
I need some other information, but when you run `pyvue` you need to be inside the django project directory (where there's the `manage.py` command).

In fact:
```
$ virtualenv env
...
(env) $ pip install django
...
(env) $ pip install python-vuejs
...
(env) $ django-admin startproject myproject
...
(env) $ cd myproject
(env) $ pyvue djstartvueapp frontend
...
```
It works.

**Comment by cstrap** [comment]
Btw, I noticed that with the new version of node something went wrong launching the command `pyvue djstartvueapp myapp`.
I fix this asap.

**Comment by cstrap** [comment]
Fixed. I added also a better error message when the user run the command outside the django project directory.
